### ISSUE TITLE
Add v3ddriver/glesv2/egl to gbue4k

### ISSUE THREAD

**Issue by wolfgangmauer** [mohousch/NeutrinoNG#1]
Headers: https://source.mynonpublic.com/gigablue/v3ddriver/gb-nexus-headers.zip
Libs: https://source.mynonpublic.com/gigablue/v3ddriver/gb7252-v3ddriver-20200723.r0.zip

THX

**Comment by mohousch** [comment]
Done,

plz check if it works?

**Comment by wolfgangmauer** [comment]
Fits so far ;-)
Shouldn't there be pkg-config files for egl/gles2 ?
