### ISSUE TITLE
Infinite boot/reboot loop after flashing from usb

### ISSUE THREAD

**Issue by wolfgangmauer** [mohousch/NeutrinoNG#2]
With the gbue4k neutrino and neutrino2 image goes into infinite boot/reboot loop.

**Comment by mohousch** [comment]
how big is the rootfs?

dieses Verhalten kam direkt nach dem buildsystem neu aufsetzen, obwohl das ist 1:1 zu den alten buildsystem hier will der bootloder den rootfs nicht wenn der kleiner als 70MB
um das zu umgehen bevor das make image-* baue die beide GUIs um einen grosseren rootfs zu bekommen

**Comment by wolfgangmauer** [comment]
With building neutrino & neutrino2 the flashing works, but the rootfs is still < 70MB
![grafik](https://github.com/user-attachments/assets/d79ad1f0-538b-4072-9bb6-6761939831e2)

**Comment by mohousch** [comment]
kannst du einen seriellen log vom boot machen?

BTW:
kannst Du vom dem alten buildsystem ein image bauen?
https://github./com/mohousch/buildsystem.saved

**Comment by wolfgangmauer** [comment]
seriellen log geht nicht, wer hat schon noch ein serielles kabel? :-)
Mit dem alten ein image-neutrino oder image-neutrino2

Ein "nur" image-neutrino2 mit dem buildsystem.saved geht auch in eine reboot-schleife
Ist mir wohl bis jetzt nicht augefallen, da ich immer neutrino & neutrino2 gebaut habe....

**Comment by mohousch** [comment]
Strange

**Comment by wolfgangmauer** [comment]
Die gbue4k hat keinen seriellen Port, wie komme ich da an ein log vom boot ?

**Comment by mohousch** [comment]
das ist doof , der ist bestimmt noch auf die Platine und das ist viel Bastel Arbeit den UART bzw seriell Anschluss zu suchen 
Bootet immer noch nicht ?

**Comment by wolfgangmauer** [comment]
Nö

**Comment by mohousch** [comment]
das ist sehr komisch
kannst Du das vielleicht abgrenzen ab wann diese Fehler angefangen hat?

**Comment by wolfgangmauer** [comment]
Leider nicht, da ich von anfang an immer zuerst neutrino und dann erst neutrino2 gebaut habe
ntpdate problem?

**Comment by mohousch** [comment]
laut Gigablue der RS-232 Port ist intern, Falls man Glück hat ist bezeichnet und die Pins sind gelötet und auch bezeichnet sonst wird das zu viel Bastel Arbeit, denn braucht man einen seriell UART-USB Adapter Kabel, auf Linux braucht man minicom und Windows putty eignet sich gut

**Comment by wolfgangmauer** [comment]
Wenn man nun noch die pinbelegung kennen würde ;-)
![PXL_20240915_122048450](https://github.com/user-attachments/assets/fda9a21e-7d62-422f-92d3-3321a21faa0a)

**Comment by mohousch** [comment]
Meistens GND und 3.3V sind der erste und letzte

ich tippe so:
wo j21 steht ist der GND der letzte ist 3.3 V TX und RX versuch es mal so mal so

**Comment by mohousch** [comment]
Ich glaube ich hab es

ich koennte es gerade hier nachreproduzieren

nicht alle libs werden kopiert.
